# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2df80f2677722f30078eed23e12e7ca219a7e8afb2690c27166bcbc444a259325adc56610fd2495da3114cc454be764c5b91307e7e91fe720708bec90ddb5dc3

test:
  secret_key_base: 8942473695a0210c669b8f0b6d902a25de8a34aef894ef361d7eb360ede31d0006fa46dcd4e099c3ba6d82f6c6f1a6d7921a261e856dec279d246bef2d0238ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
